name: Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        target: ['16', '18', '20']
    uses: snapshot-labs/actions/.github/workflows/test.yml@main
    with:
      target: ${{ matrix.target }}
